# ----------------------------------------------------------------------------------
#                      r u s t f m t   -   C O N F I G
# ==================================================================================

# Maximum width of each line.
max_width = 100

# Number of spaces per tab.
tab_spaces = 4

# Maximum width of the args of a function call before
fn_call_width = 80

# Maximum width in the body of a struct lit before falling back to vertical formatting.
struct_lit_width = 60

# Maximum width in the body of a struct variant before falling back to vertical formatting.
struct_variant_width = 60


